### PR TITLE
hlint 2.0 handles hint configuration via .hlint.yaml files

### LINKED ISSUE #30: Incompatibility with >=hlint-2.0
linter-hlint seems to be incompatible the with current hlint (2.0.8).

With the default settings it crashes with:
```
[Linter] Error running HLint Error: hlint: user error (Failed to find requested hint files:
  Default
  Dollar
  Generalise
)
```
It seems that the values accepted by the `--hint` option changed with hlint-2.0.

(As a workaround I discovered that you can put a empty file (like /dev/null) in the "List of hints to use" field on the linter-hlint config page.)

### PR DESCRIPTION
**Pull request by mkoloberdin**
See: https://github.com/ndmitchell/hlint/blob/master/data/default.yaml
Fixes #30

### CODE REVIEW

**Comment by Arcanemagus** [comment]
So HLint 2.0 no longer allows specifying the hints on the CLI _at all_?

**Comment by mkoloberdin** [comment]
It looks that way. See e.g. these commits:
1. https://github.com/ndmitchell/hlint/commit/11eacb9b3d887a5b145f0abf4d5af066eb4ecd73
2. https://github.com/ndmitchell/hlint/commit/a0acdf58d165598dd6ff760762d198d9c631f388

**Comment by Arcanemagus** [comment]
That's for the configuration files, in part of this PR you are removing the setting that allows specifying default hints using `--hint=hintName`.

**Comment by mkoloberdin** [comment]
Wasn't the "hintName" merely a reference to a correspondent "data file?"
E.g.:
--hint=Dollar -> data/Dollar.hs
(removed in this commit: https://github.com/ndmitchell/hlint/commit/11eacb9b3d887a5b145f0abf4d5af066eb4ecd73 )

It appears that these files (data/{Default,Dollar,Generalise}.hs) were consolidated and the new method of configuration (via yaml files) was added instead.

**Comment by Arcanemagus** [comment]
Makes sense to me!

**Pull request merged**
